---
- name: Wait for SSH
  hosts: all
  gather_facts: no # Très important car on ne peut pas encore collecter les facts
  tasks:
    - name: Wait for port 22 to become available
      delegate_to: localhost
      ansible.builtin.wait_for:
        host: "{{ ansible_host }}"
        port: 22
        timeout: 300

- hosts: all
  become: yes
  tasks:
    - name: Mise à jour des paquets
      apt:
        update_cache: yes
        upgrade: dist

    - name: Installation de fail2ban
      apt:
        name: fail2ban
        state: present

    - name: Installation des dépendances Docker
      apt:
        name: [apt-transport-https, ca-certificates, curl, software-properties-common]
        state: present

    - name: Ajout de la clé GPG Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Ajout du dépôt Docker
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu noble stable
        state: present

    - name: Installation de Docker Engine
      apt:
        name: [docker-ce, docker-ce-cli, containerd.io, docker-compose-plugin]
        state: present

    - name: Ajouter l'utilisateur ubuntu au groupe docker
      user:
        name: ubuntu
        groups: docker
        append: yes
    
    - name: Installation de python3-docker (requis pour les modules Ansible)
      apt:
        name: python3-docker
        state: present
        update_cache: yes
      tags:
        - swarm

    - name: Installer nfs-common
      apt:
        name: nfs-common
        state: present 

- name: Configurer le serveur NFS sur le Manager
  hosts: manager
  become: yes
  tasks:
    - name: Installer le serveur NFS
      apt:
        name: nfs-kernel-server
        state: present

    - name: Créer le dossier partagé pour Etherpad
      file:
        path: /var/nfs/etherpad_data
        state: directory
        mode: '0777'

    - name: Configurer les exports NFS
      lineinfile:
        path: /etc/exports
        line: "/var/nfs/etherpad_data *(rw,sync,no_subtree_check,no_root_squash)"
      notify: Restart NFS

  handlers:
    - name: Restart NFS
      service:
        name: nfs-kernel-server
        state: restarted
    

- hosts: manager
  become: yes
  tasks:
    - name: Init Swarm
      community.general.docker_swarm:
        state: present
      register: swarm_info

    - name: Sauvegarder le Join Token Worker
      set_fact:
        worker_token: "{{ swarm_info.swarm_facts.JoinTokens.Worker }}"

- hosts: workers
  become: yes
  vars:
    # On récupère le token depuis la mémoire du groupe manager
    manager_ip: "{{ hostvars[groups['manager'][0]]['ansible_host'] }}"
    token: "{{ hostvars[groups['manager'][0]]['worker_token'] }}"
  tasks:
    - name: Join Swarm
      community.general.docker_swarm:
        state: join
        join_token: "{{ token }}"
        remote_addrs: [ "{{ manager_ip }}:2377" ]
    
- hosts: manager
  become: yes
  tasks:
    # --- Stack Traefik ---
    - name: Générer le fichier de stack Traefik
      ansible.builtin.template:
        src: ./templates/traefik-stack.yml.j2
        dest: /home/ubuntu/traefik-stack.yml

    - name: Déployer la stack Traefik
      shell: docker stack deploy -c /home/ubuntu/traefik-stack.yml traefik

    # --- Stack Whoami ---
    - name: Générer le fichier de stack Whoami avec l'IP dynamique
      ansible.builtin.template:
        src: ./templates/app-whoami-stack.yml.j2
        dest: /home/ubuntu/app-whoami-stack.yml
    
    - name: Déployer la stack Whoami
      shell: docker stack deploy -c /home/ubuntu/app-whoami-stack.yml whoami

    # --- Stack Ehterpad ---
    - name: Générer le fichier de stack Ehterpad avec les IPs dynamiques
      ansible.builtin.template:
        src: ./templates/app-etherpad-stack.yml.j2
        dest: /home/ubuntu/app-etherpad-stack.yml
    
    - name: Déployer la stack Ehterpad
      shell: docker stack deploy -c /home/ubuntu/app-etherpad-stack.yml etherpad